sudo: required
services:
  - docker

before_install:
  - docker build -t taj9ahmed/docker-react -f Dockerfile.dev .

script:
  - docker run taj9ahmed/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-v2"
  env: "DockerReactV2-env"
  bucket_name: "elasticbeanstalk-eu-north-1-709234954052"
  bucket_path: "docker-react-v2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY